application: tokibito-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /presentation/create
  script: main.application
  login: admin

- url: .*
  script: main.application

builtins:
- deferred: on
- appstats: on
- remote_api: on

libraries:
- name: webob
  version: latest
- name: django
  version: latest
